FROM node:18

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

RUN npm install -g nodemon

COPY . .

EXPOSE 5000

# Startuj server koristeći nodemon za praćenje promena
CMD ["nodemon", "server.js"]
